# Generated by Django 2.2.6 on 2019-10-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='target_cd',
            new_name='target_ct',
        ),
    ]
